export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_PROFILE = "SET_PROFILE";
export const DESTROY_ACCESS_TOKEN = "DESTROY_ACCESS_TOKEN";
export const DESTROY_PROFILE = "DESTROY_PROFILE";
export const SET_IMAGES = "SET_IMAGES";
